-- AlterTable
ALTER TABLE "Story" ALTER COLUMN "estimate" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingEffort" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "UserProjectCapacity" ALTER COLUMN "capacity" SET DEFAULT 0,
ALTER COLUMN "capacity" SET DATA TYPE DOUBLE PRECISION;

-- AlterTable
ALTER TABLE "Worklog" ALTER COLUMN "effort" SET DATA TYPE DOUBLE PRECISION,
ALTER COLUMN "remainingEffort" SET DATA TYPE DOUBLE PRECISION;
